### ISSUE TITLE
"Acquiring location" goes forever, breaks app

### ISSUE THREAD

**Issue by makbol** [jsynowiec/airqmon#50]
Sometimes it's able to acquire location, sometimes not and I can't use app. Maybe instead of automatic location, allow user to manually input sensor via settings?

I'd to help but local development guide is missing :(. Not sure what I need to be fully able to locally develop.

**Comment by lukas085** [comment]
I have the same problem.

**Comment by mszymczak-silvair** [comment]
same, unable to get the location on 3 devices :/

**Comment by RudolfTheOne** [comment]
same, unable to get the location on 3 devices :/

**Comment by makbol** [comment]
@lukas085 @RudolfTheOne @mszymczak-silvair check out my fix :)

**Comment by RudolfTheOne** [comment]
Wow, you are a real savior, thank you @makbol!
@jsynowiec will you release the new version soon?

**Comment by jsynowiec** [comment]
I am unable to reproduce this issue. Can you provide more details?

**Comment by RudolfTheOne** [comment]
This is what I see (since ~Dec 2021) - it keeps acquiring location forever.

<img width="307" alt="Screenshot 2022-01-10 at 11 17 06" src="https://user-images.githubusercontent.com/51971616/148750000-fe15cbef-9bcd-49ca-85c5-75018bb841a8.png">

**Comment by jsynowiec** [comment]
Thanks, I have found what the issue is. I could not reproduce it because I am using a different Google API key than the one included in the binaries. The account I was using to sustain the open-source free release ran out of credits in 2021, so it will not work anymore because the Geolocation API is not a free service. Also, the DigitalOcean's account, which hosts the Airqmon API droplet, will run out of credits in March, and the API will stop functioning.

For transparency, the monthly costs for Airqmon were about 50$, and I am no longer willing to cover that. I covered a lot since November 2017 out of my pocket, while the only received support was from the @digitalocean open-source program and one-time donations from @thymikee and @kdzwinel. I could offset some using the free credits until now, but that's no longer an option 🤷🏼‍♂️ 

I have removed all binaries from the current and previous releases as they will no longer work. You can clone the latest release and build your own version while providing a working Google API key. The Airqmon API will keep functioning for a month or two more.

**Comment by thymikee** [comment]
Sad to hear it, but I totally feel you @jsynowiec. Thanks for all the time and support you provided and for keeping the app in the open. Appreciated <3

**Comment by jsynowiec** [comment]
I found a free geolocation service that does not require a key. Please check the [v2.1.1](https://github.com/jsynowiec/airqmon/releases/tag/v2.1.1) release. I will remove the pre-release flag if it works for you.

**Comment by makbol** [comment]
Thanks for providing context. As you mentioned, even if you fix the geolocation error there's still API service which will run out of founds in March so changing location service will not fix that issue or maybe just temporarily.

Regarding new geolocation service - I tried and I'm getting an error - "communication error". I inspected that and it seems it's and Airqmon API issue
![Zrzut ekranu 2022-01-10 o 15 29 57](https://user-images.githubusercontent.com/5435685/148822229-161828ce-be5d-467b-9454-6f6cb7b285f7.png)

**Comment by jsynowiec** [comment]
@makbol, I would say that this is an issue with the data returned from Airly. I used your IP address and location to check the response, and you can see the same sensor station on the screenshot.

![image](https://user-images.githubusercontent.com/1029142/148929236-b873067c-03a9-4826-90fe-d6e8520edfa2.png)

I have seen in logs that some sensor stations can disappear or return incorrect data even if the station shows correctly on Airly's map 🤷🏼‍♂️ 

> As you mentioned, even if you fix the geolocation error there's still API service which will run out of founds in March so changing location service will not fix that issue or maybe just temporarily.

Well, it turned out that there was no error to start with 😉 The geolocation code in 2.1.0 works just fine. There is a different kind of issue, but I explained that in my previous comment. 

With the latest commits, I just tried to provide an alternative to those who cannot or do not want to pay for the Google API 😄  We will see what happens regarding the API. There are still a few months of credits left.

**Comment by makbol** [comment]
I meant, the issue with geolocation :). Looks like it, with new location API it's working fine now although I'm getting station which is not close to my real location. How about introducing manual mode (as an option for more advanced users) which would enable manually picking station?

btw. can you please remove my ip address from screenshot?
